name: "intersurvie"
version: 1.1.5
main: pocoyo.intersurvie.PluginMain
author: pocoyo
api-version: 1.16
description: "Allows users to claim land easily!"
commands:
   claim:
      description: "Allows you to claim land!"
      permission: intersurvie.claims.claimChunk
      permission-message: "perm : intersurvie.claims.claimChunk"
   trust:
      description: "Trust someone on a chunk of land, gives them all permissions"
      permission: intersurvie.claims.trustPlayer
      permission-message: "perm : intersurvie.claims.trustPlayer"
   untrust:
      description: "Untrust someone on a chunk of land, removes all of their permissions"
      permission: intersurvie.claims.untrustPlayer
      permission-message: "perm : intersurvie.claims.untrustPlayer"
   unclaim:
      description: "Allows you to unclaim land"
      permission: intersurvie.claims.unclaimChunk
      permission-message: "perm : intersurvie.claims.unclaimChunk"
   rtp:
      description: "teleports randomly"
      permission: intersurvie.player.rtp
      permission-message: "perm : intersurvie.player.rtp"
   debug-claim:
      description: "debug claim"
      permission: intersurvie.debug.claim
      permission-message: "perm : intersurvie.debug.claim"
permissions:
   intersurvie.claims.*:
      description: Gives access to all Claim permissions
      children:
         intersurvie.claims.claimChunk: true
         intersurvie.claims.unclaimChunk: true
         intersurvie.claims.unclaimChunkAdmin: true
         intersurvie.claims.bypassProtection: true
         intersurvie.claims.trustPlayer: true
   intersurvie.claims.claimChunk:
      description: Allows you to Claim a chunk of land
      default: true
   intersurvie.claims.unclaimChunk:
      description: Allows you to Unclaim a chunk of land that is yours
      default: true
   intersurvie.claims.unclaimChunkAdmin:
      description: Allows you to Unclaim a chunk that isnt yours
      default: op
   intersurvie.claims.bypassProtection:
      description: Allows you to bypass the protection
      default: op
   intersurvie.claims.trustPlayer:
      description: Allows you to trust someone on your chunk
      default: true
   intersurvie.claims.untrustPlayer:
      description: Allows you to untrust someone from your chunk
      default: true
   intersurvie.rtp:
      description: Allows you to randomly teleport
      default: true
   intersurvie.misc.cooldownBypass:
      description: Allows you to bypass cooldown
      default: op

