# Configuration
rtp-cooldown : 300 # (INT) | Seconds

# Messages
fatal-error : "fatal-error" # (STRING) | When an unrecognized error happens
cooldown : "cooldown" # (STRING) | When player is still on cooldown for command (Applies to every command) | $TIME_REMAINING$ Seconds left on cooldown

rtp-teleport : "rtp-teleport" # (STRING) | When player get teleported | $X$ Coords X - $Y$ Coords Y - $Z$ Coords Z

unclaim-chunk : "unclaim-chunk" # (STRING) | When player unclaims a chunk
unclaim-notowner : "unclaim-notowner" # (String) | Player tried to modify chunk that isnt theirs
unclaim-notclaimed : "unclaim-notclaimed" # (STRING) | Chunk isnt claimed, and cant be unclaimed

claim-chunk : "claim-chunk" # (String) | Player claimed a chunk
claim-notavailable : "claim-notavailable" # (STRING) | Chunk is already claimed

claim-notaplayer : "claim-notaplayer" # (STRING) | Username given isnt a player/player isnt connected | $PLAYER$ isnt a player
claim-successfullyadded : "claim-successfullyadded" # (STRING) | $PLAYER$ has successfully been added to chunk
claim-successfullyremoved : "claim-successfullyremoved" # (STRING) | $PLAYER$ has successfully been removed from chunk
claim-chunkclaimed : "claim-chunkclaimed" # (STRING) | Chunk is claimed, no interaction permitted
